### ISSUE TITLE
【建议】可以将箭头上下居中

### ISSUE THREAD

**Issue by FrzMtrsprt** [singleNeuron/QsCompass#2]
### 描述
希望可以将指北箭头上下居中，同时将箭头略为缩小一点，可以调整一下箭头样式，个人认为这样更加美观，同时也更加省电。
### 截图
<div>
<img src="https://user-images.githubusercontent.com/15852717/111775062-3a325000-88eb-11eb-9849-e4cd33f62e4f.png" width = "200" height = "200" alt="实际界面截图" align=center />
==>
<img src="https://user-images.githubusercontent.com/15852717/111775818-33580d00-88ec-11eb-8ac1-090e48866dd6.jpg" width = "200" height = "200" alt="修改界面截图" align=center />
</div>

### 手表型号
Fossil Sport 43mm

**Comment by Cryolitia** [comment]
https://github.com/singleNeuron/QsCompass/commit/8ba8a6bda8d6f7ac7e2e76ec263807f88e83982a

![image](https://user-images.githubusercontent.com/23723294/111811112-af188080-8911-11eb-973f-83004c65f0dd.png)
